# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT

services:
  app:
    container_name: test-radar
    image: test-radar:dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: uv run python src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - SECRET_KEY=secret
      - DEBUG=true
      - REGISTRATION_ENABLED=false
