# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT

services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: test_radar
      POSTGRES_USER: test_radar
      POSTGRES_PASSWORD: test_radar
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_radar"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:
    container_name: test-radar
    image: test-radar:dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: uv run python src/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SECRET_KEY=secret
      - DEBUG=true
      - REGISTRATION_ENABLED=false
      - DATABASE_URL=postgres://test_radar:test_radar@db:5432/test_radar

volumes:
  pgdata:
