# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT

[project]
name = "test-radar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==6.0.7",
    "django-stubs==6.0.7",
    "djangorestframework==3.17.1",
    "django-debug-toolbar==7.0.0",
    "gunicorn==26.0.0",
    "httpx==0.28.1",
    "pytest==9.1.1",
    "django-environ==0.14.0"
]

[tool.setuptools.packages.find]
where = ["."]

[dependency-groups]
dev = [
    "djangorestframework-stubs==3.17.0",
    "mypy==2.3.0",
    "ondivi==0.7.3",
    "ruff==0.16.0",
    "wemake-python-styleguide==1.7.0",
    "pytest-cov==7.1.0",
    "pytest-django==4.12.0",
    "deltaver==1.0.2",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "server.settings"
pythonpath = ["src"]
# radar_endpoint = 'http://127.0.0.1:8000'

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
mypy_path = "src"
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "server.settings"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN101",
  "ANN401",
  "D1",
  "D203",
  "D213",
  "ERA001",
  "FIX002",
  "PGH003",
  "Q000",
  "RUF012",
  "RUF100",
  "S105",
  "S603",
  "S607",
  "TD002",
  "TD003",
  "TD004",
  "UP022",
  "UP032"
]
exclude = [
  "manage.py",
  "*/migrations/*",
]
external = [
  "WPS",
]

[tool.ruff.lint.per-file-ignores]
"src/tests/**/*.py" = ["ARG001", "FLY002", "PLR2004", "S101"]

[tool.ruff.format]
quote-style = "single"

[tool.poetry.group.dev.dependencies]
django-stubs = {extras = ["compatible-mypy"], version = "^5.2.0"}

