# Generated by Django 5.2.3 on 2025-06-17 17:35

import records.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                (
                    'id',
                    models.CharField(
                        default=records.models._hex_token,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name='Indentifier',
                    ),
                ),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
                ('success', models.BooleanField(verbose_name='Success')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('logs', records.models.CompressedTextField(blank=True, verbose_name='Logs')),
            ],
            options={
                'verbose_name': 'Test record',
                'verbose_name_plural': 'Test records',
            },
        ),
    ]
