# Generated by Django 5.2.3 on 2026-07-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='branch',
            field=models.CharField(max_length=512, verbose_name='Git branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrecord',
            name='commit',
            field=models.CharField(max_length=40, verbose_name='Git commit'),
            preserve_default=False,
        ),
    ]
