# Generated by Django 6.0.7 on 2026-07-28 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('records', '0003_merge_20260728_0702'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                (
                    'type',
                    models.CharField(
                        choices=[('ci', 'CI'), ('local', 'Local')], max_length=10, verbose_name='Agent type'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='agents',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Owner',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='agents',
                        to='records.project',
                        verbose_name='Project',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.AddField(
            model_name='testrecord',
            name='agent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='records',
                to='records.agent',
                verbose_name='Agent',
            ),
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128, verbose_name='Token hash')),
                ('token_mask', models.CharField(max_length=32, verbose_name='Token mask')),
                ('scopes', models.CharField(default='write:results', max_length=255, verbose_name='Scopes')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last used at')),
                ('last_used_ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='Last used IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                (
                    'agent',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='token',
                        to='records.agent',
                        verbose_name='Agent',
                    ),
                ),
            ],
            options={
                'verbose_name': 'API token',
                'verbose_name_plural': 'API tokens',
            },
        ),
    ]
