# Generated by Django 6.0.7 on 2026-07-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('records', '0004_agents_and_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='last_used_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Last used IP'),
        ),
    ]
