# Generated by Django 6.0.7 on 2026-07-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('records', '0006_alter_testrecord_id_testsession_testrecord_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='label',
            field=models.TextField(verbose_name='Label'),
        ),
    ]
