# Generated by Django 6.0.7 on 2026-08-01 09:40

from typing import final

from django.db import migrations, models


@final
class Migration(migrations.Migration):
    dependencies = [
        ('records', '0007_alter_testrecord_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='logs',
            field=models.BinaryField(blank=True, verbose_name='Logs'),
        ),
    ]
