# Generated by Django 6.0.7 on 2026-07-30 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_testrecord_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='records.testsession', verbose_name='Test session'),
        ),
    ]
