# Generated by Django 6.1 on 2026-08-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_session_env_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='status',
            field=models.CharField(choices=[('flaky', 'Flaky')], default=1, max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
