# Generated by Django 6.1 on 2026-08-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_testrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='status',
            field=models.CharField(choices=[('flaky', 'Flaky')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
