# Generated by Django 6.1 on 2026-08-10 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('records', '0012_alter_testrecord_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('name', 'project'), name='uniq_agent_name_per_project'),
        ),
    ]
