# Generated by Django 6.1 on 2026-08-11 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('records', '0013_agent_uniq_name_per_project'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='status',
        ),
    ]
