# Generated by Django 6.1 on 2026-08-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_populate_memberships'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testrecord',
            index=models.Index(fields=['project', 'timestamp'], name='records_tes_project_f0d5b3_idx'),
        ),
    ]
