# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT

services:
  test-radar-http-blue:
    image: blablatdinov/test-radar:${TAG_NAME}
    command: .venv/bin/gunicorn server.wsgi:application -b 0.0.0.0:8012
    restart: always
    ports:
      - "8012:8012"  # Blue экземпляр
    env_file:
      - .env
    environment:
      - APP_VERSION=${TAG_NAME}
      - DEPLOY_COLOR=blue
    networks:
      - test-radar-network
    labels:
      - "deploy.color=blue"
      - "deploy.version=${TAG_NAME}"

  test-radar-http-green:
    image: blablatdinov/test-radar:${TAG_NAME}
    command: .venv/bin/gunicorn server.wsgi:application -b 0.0.0.0:8013
    restart: always
    ports:
      - "8013:8013"  # Green экземпляр
    env_file:
      - .env
    environment:
      - APP_VERSION=${TAG_NAME}
      - DEPLOY_COLOR=green
    networks:
      - test-radar-network
    labels:
      - "deploy.color=green"
      - "deploy.version=${TAG_NAME}"

networks:
  test-radar-network:
    driver: bridge
