# SPDX-FileCopyrightText: Copyright (c) 2015-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT
---
name: Ensure tests are updated
on:
  pull_request:
    branches: [ "master" ]

jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Filter changes
      id: filter
      uses: dorny/paths-filter@v4
      with:
        filters: |
          py-code:
            - 'src/**/*.py'
          py-tests:
            - 'src/tests/**/*.py'
          js-code:
            - 'src/gui/static/js/**/*.js'
            - '!src/gui/static/js/**/*.test.js'
          js-tests:
            - 'src/gui/static/js/**/*.test.js'

    - name: Ensure Python code changes have corresponding tests
      if: steps.filter.outputs.py-code == 'true' && steps.filter.outputs.py-tests != 'true'
      run: |
        echo "Error: Python code changes detected, but no test files were modified."
        exit 1
      shell: bash

    - name: Ensure JS code changes have corresponding tests
      if: steps.filter.outputs.js-code == 'true' && steps.filter.outputs.js-tests != 'true'
      run: |
        echo "Error: JS code changes detected, but no JS test files were modified."
        exit 1
      shell: bash
