name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python 3.14
      uses: actions/setup-python@v7
      with:
        python-version: 3.14
    - name: Setup uv
      uses: astral-sh/setup-uv@v9.0.0
      with:
        python-version: 3.14
        activate-environment: true
    - name: Install Dependencies
      run: uv sync --no-default-groups

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python 3.14
      uses: actions/setup-python@v7
      with:
        python-version: 3.14
    - name: Setup uv
      uses: astral-sh/setup-uv@v9.0.0
      with:
        python-version: 3.14
        activate-environment: true
    - name: Install Dependencies
      run: uv sync --no-default-groups
    - name: Lint with ruff
      run: uv run ruff check src
    - name: Lint with flake8
      run: uv run flake8 src
    - name: Lint with mypy
      run: |
        DATABASE_URL=sqlite:///:memory: uv run mypy src

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: test_radar
          POSTGRES_USER: test_radar
          POSTGRES_PASSWORD: test_radar
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python 3.14
      uses: actions/setup-python@v7
      with:
        python-version: 3.14
    - name: Setup uv
      uses: astral-sh/setup-uv@v9.0.0
      with:
        python-version: 3.14
        activate-environment: true
    - name: Install gettext
      run: sudo apt-get update && sudo apt-get install -y gettext
    - name: Install Dependencies
      run: uv sync --all-groups
    - name: Check translations are up to date
      run: |
        DATABASE_URL=sqlite:///:memory: uv run django-admin makemessages -l ru -l en --no-location --no-wrap
        git diff --exit-code --ignore-matching-lines='^"POT-Creation-Date' -- locale/
      working-directory: src
    - name: Create static dir
      run: mkdir static
    - name: Test
      run: uv run pytest src/tests -vv
      env:
        DATABASE_URL: postgres://test_radar:test_radar@localhost:5432/test_radar
        RADAR_TOKEN: ${{ secrets.TEST_RADAR_TOKEN }}
        REGISTRATION_ENABLED=true

  deltaver:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python 3.14
      uses: actions/setup-python@v7
      with:
        python-version: 3.14
    - name: Setup uv
      uses: astral-sh/setup-uv@v9.0.0
      with:
        python-version: 3.14
        activate-environment: true
    - name: Install Dependencies
      run: uv export > requirements.txt
    - name: Run deltaver
      run: uv run deltaver requirements.txt --format pip-freeze
